### ISSUE TITLE
Request to use Git tags/releases for versioning

### ISSUE THREAD

**Issue by msurguy** [bit101/gifloopcoder#10]
I would like to ask the project maintainer to use Github tags / releases to create a semantic way of project maintenance which would allow to see what has changed from version to version. Creating a new release is easy and only requires a few clicks in Github UI but two main benefits of doing it are: 

- You can link to a download of a specific release (and avoiding using your own servers and FTP uploads), for example: https://github.com/CodepadME/laravel-tricks/releases 
- When a new release is created, you can specify to create a new GIT tag which would make it very easy to compare two versions of the software and to see what has changed between them.

If you need help on how to create releases, here it is:
https://help.github.com/articles/creating-releases/

**Comment by bit101** [comment]
Nice. I didn't know about that feature.
