### ISSUE TITLE
Parenting breaks phasing (with suggested fix)

### ISSUE THREAD

**Issue by Landerson352** [bit101/gifloopcoder#12]
@bit101 I apologize for the formatting of this issue, I just noticed it and am having trouble getting the build running for a proper pull request. I thought you'd want to know about it.

In the following scenario, one would expect the two rows of boxes to appear identically in animation, only shifted vertically. However, the top row "waves" while the bottom row runs synchronously. (Any similar demo with phased items in a container will reveal the same issue.)

![image](https://cloud.githubusercontent.com/assets/5214462/11996082/8bb5eea0-aa2a-11e5-9022-1032eef938a5.png)

This is caused by the `skipInterpolation` flag passed through to children. It is in place to prevent easing being re-applied recursively, but it interferes with the shapes' individual phasing. 

One suggested fix is to change how this is handled, so that the "actual time" is always passed through to children, while the "transformed time" is used only for drawing in the current context:

![image](https://cloud.githubusercontent.com/assets/5214462/11996077/6da2c6d6-aa2a-11e5-9b57-8ad90d0e48df.png)

I have not fully vetted this solution, but it does fix the above scenario. I'm hoping it's a good starting point. Thanks!

**Comment by bit101** [comment]
I noticed that myself and had a go at fixing it earlier on. The things I tried made it worse, but I didn't go too deeply into it. I'll take a look at this and see if it Shirts things out.

**Comment by bit101** [comment]
Looks good. Implemented this.

**Comment by Landerson352** [comment]
Excellent! I noticed that the build hadn't been recompiled in that commit. Is that typically something you do every time?

**Comment by bit101** [comment]
yeah, like I said in another issue, still working out the build process. I tend to go minimal until the need arises for something else. The need is arising.
