### ISSUE TITLE
App is wrongly named in releases 1.3.2 and 1.3.3

### ISSUE THREAD

**Issue by vitorgalvao** [bit101/gifloopcoder#17]
In release `1.3.1`, getting the latest OS X zip will give us `GIFLoopCoder.app` (the correct name). However, in versions `1.3.2` and `1.3.3`, the zip contains `Electron.app` instead.

Perhaps something changed in your release process that is no longer performing the correct rename?

**Comment by bit101** [comment]
Yeah, updated and forgot to change the name. Fixed for 1.3.3. Didn't figure a simple name change warranted a new build number.
