### ISSUE TITLE
Edge case (?) where GIF does not render properly

### ISSUE THREAD

**Issue by roytanck** [bit101/gifloopcoder#2]
I was playing with GLC last night when I noticed that the GIF didn't render properly for the code below.

```
function onGLC(glc) {
	glc.loop();
	// glc.playOnce();
	glc.size(400, 400);
	glc.setDuration(2);
	glc.setFPS(30);
	glc.setMode("single");
	glc.setEasing(false);
	glc.setMaxColors(8);
	var list = glc.renderList,
		width = glc.w,
		height = glc.h,
		color = glc.color;

	// your code goes here:
	var nr = 6;

	for( var x=0; x<nr+2; x++ ){
		for( var y=0; y<nr+2; y++ ){
			var r = Math.min( 255, Math.floor( x * 32 ) );
			var g = Math.min( 255, Math.floor( y * 32 ) );
			var b = 0;
			list.addRect({
				x: x*(width/nr) - (width/nr)/2,
				y: y*(height/nr) - (height/nr)/2,
				w: 68,
				h: 68,
				rotation: [ 0, 90 ],
				fill: true,
				stroke: false,
				/*fillStyle: color.rgba( r, g, b, 1 ),*/
				fillStyle: 'rgba(' + r + ',' + g + ',' + b + ',1)',
			});
		}
	}

}
```

I've tested this in both Firefox and Chrome, on Windows 10 and Ubuntu. In each case the GIF has the same weird flickering effect.

![gifissue](https://cloud.githubusercontent.com/assets/1642390/11363154/5ca8c74e-9298-11e5-82fa-9b953cd306eb.gif)

Any ideas what causes this to happen?

**Comment by bit101** [comment]
It's the max colors being so low. You are trying to animate smoothly
between colors. So on each frame there is an algorithm that chooses the
best color for each pixel. But it only has a color palette of eight colors
to choose from. Increase max colors and that will go away.

**Comment by roytanck** [comment]
Ah yes, that makes sense. That setting was still there from an earlier, monochrome, experiment. Thank you.

My bad.

**Comment by bit101** [comment]
Ah yeah, I saw that you were calculating colors and thought it was to animate them. But yeah, you'll get that anyway with really small palettes. That's part of the GIF encoder stuff that I didn't write. It compares each pixel against the palette on each frame and determines the best one to use. Not really sure why it's choosing a different one each time for the same shape. There's also a quality setting on the encoder that I haven't exposed. HIgher quality values apparently do better at color quanitzation, but take longer to encode. It's at the default level now. I may expose that as a hidden setting later. Not in the ui though. I think that for the casual user, it would cause more problems than it would solve.

**Comment by roytanck** [comment]
I don't know whether the GIF quality settings include "Photoshop-like" things like dithering. If so, it could be worth exposing them to the user, because dithering has a huge impact on file size. Currently, I think the quality is excellent.
