### ISSUE TITLE
Use NPM for cross platform build process

### ISSUE THREAD

**Issue by msurguy** [bit101/gifloopcoder#5]
Currently a .bat file is used for the build process which doesn't work on Mac OS. This could be made cross platform by using NPM which a lot of web developers already have installed on their machines. Then, you could just include your default build commands in the `package.json` file like so:

```js
{
  "name": "gifloopcoder",
 ...
  "scripts": {
    "build": "r.js -o build.js"
  },
  ...
}
```

Then you can just run `npm run build` to build.

**Comment by msurguy** [comment]
Further, you could use Gulp.js for live reloading and building on the fly while you develop.

**Comment by bit101** [comment]
the bat file was just a quick solution. it will be changing and be more flexible. at this point it doesn't need any complex build system.
