### ISSUE TITLE
Create docs in Markdown instead of HTML

### ISSUE THREAD

**Issue by msurguy** [bit101/gifloopcoder#6]
I suggest converting the current documentation to Markdown format and storing it here as markdown since that would make PRs and modifications in docs a breeze for everybody. 

If you want help with that, I'd be happy to do the conversion and integrating a build script that would then build new HTML docs on markdown changes.

**Comment by bit101** [comment]
That's a great idea. I've written a whole book in markdown and then used scripts to convert to html/mobi/epub/pdf for publication. I was stupid not to think of using markdown for the docs here. If you want to do that conversion, that would be great. Otherwise, I'll get around to it eventually.

**Comment by bit101** [comment]
Finally got around to this one.
